# This idea is taken from:
# https://www.rizzonicola.com/sphinx-docker/
version: "3"
services:
  service_doc:
    container_name: Learning-Compendium
    build: docker/docs
    volumes:
      - ./docs/source:/etc/Sphinx/source
      - ./docs:/etc/Sphinx/build
    ports:
      - 8100:80